---
server:
  port: ${port:8000}
security:
  user:
    password: passwrd
logging:
  level:
    com.bicjo.sample: DEBUG
    org.springframework.security: DEBUG

spring.mustache:
  prefix: classpath:/templates/
  suffix: .html